### ISSUE TITLE
デプロイ時、テーブル名に指定したstageが反映されない問題

### ISSUE THREAD

**Issue by shimoch-214** [shimoch-214/todo_api#14]
# 起こっている事

serverless.ymlにてテーブル名の末尾にstageの名称を加えるようにしているが、`--stage beta`等のオプションをつけてデプロイした際に反映されず"dev"となる。一方apiのエンドポイントやlambdaのアプリ名には反映されている。

```yml:serverless.yml
provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-northeast-1
  timeout: 10
  environment:
    usersTable: ${self:service}-users-${opt:stage, self:provider.stage}
```

ならばとserverless-state.jsonを確認すると

```json:serverless-state.json
　　// 略
      "environment": {
        "usersTable": "todo-api-users-beta",
        "tasksTable": "todo-api-tasks-beta",
        "taskListsTable": "todo-api-taskLists-beta"
      },

　　// 略
    "resources": {
      "Resources": {
        "usersTable": {
          "Type": "AWS::DynamoDB::Table",
          "Properties": {
            "TableName": "todo-api-users-beta"
```

しっかり反映されている。
いまのところ原因は不明であるが、lambdaのコンソールから環境変数と確認するとそこでも"dev"となっていた。
